#include "mqtt.h"
#include "config/device_config.h"
#include "config/mqtt_config.h"

#include <cstring>

#include "esp_log.h"
#include "mqtt_client.h"

static constexpr const char* TAG = "MQTT";

// Certificate material embedded at build time via CMakeLists.
// The linker symbols are generated by target_add_binary_data.
extern const uint8_t DEVICE_CERT_START[] asm("_binary_device_crt_start");
extern const uint8_t DEVICE_CERT_END[]   asm("_binary_device_crt_end");
extern const uint8_t DEVICE_KEY_START[]  asm("_binary_device_key_start");
extern const uint8_t DEVICE_KEY_END[]    asm("_binary_device_key_end");
extern const uint8_t ROOT_CA_START[]     asm("_binary_root_ca_pem_start");
extern const uint8_t ROOT_CA_END[]       asm("_binary_root_ca_pem_end");

static esp_mqtt_client_handle_t s_client = nullptr;
static volatile bool s_connected = false;

static void mqtt_event_handler(void* /*arg*/, esp_event_base_t /*base*/,
                               int32_t event_id, void* event_data)
{
    auto* data = static_cast<esp_mqtt_event_handle_t>(event_data);

    switch (static_cast<esp_mqtt_event_id_t>(event_id)) {
        case MQTT_EVENT_CONNECTED:
            s_connected = true;
            ESP_LOGI(TAG, "MQTT connected to %s", mqtt_config::ENDPOINT);
            break;

        case MQTT_EVENT_DISCONNECTED:
            s_connected = false;
            ESP_LOGW(TAG, "MQTT disconnected — will reconnect automatically");
            break;

        case MQTT_EVENT_PUBLISHED:
            ESP_LOGD(TAG, "MQTT publish acknowledged (msg_id=%d)", data->msg_id);
            break;

        case MQTT_EVENT_ERROR:
            s_connected = false;
            if (data->error_handle) {
                ESP_LOGE(TAG, "MQTT error: type=%d esp_tls_last_esp_err=0x%x",
                         data->error_handle->error_type,
                         data->error_handle->esp_tls_last_esp_err);
            }
            break;

        default:
            break;
    }
}

void mqtt_init()
{
    ESP_LOGI(TAG, "Starting MQTT client");
    ESP_LOGI(TAG, "Endpoint: %s", mqtt_config::ENDPOINT);
    ESP_LOGI(TAG, "Client ID: %s", config::DEVICE_ID);
    ESP_LOGI(TAG, "Topic: %s", mqtt_config::TELEMETRY_TOPIC);

    esp_mqtt_client_config_t cfg{};
    cfg.broker.address.uri            = mqtt_config::BROKER_URI;
    cfg.broker.address.port           = 8883;
    cfg.broker.verification.certificate       = reinterpret_cast<const char*>(ROOT_CA_START);
    cfg.broker.verification.certificate_len   = ROOT_CA_END - ROOT_CA_START;
    cfg.credentials.authentication.certificate     = reinterpret_cast<const char*>(DEVICE_CERT_START);
    cfg.credentials.authentication.certificate_len = DEVICE_CERT_END - DEVICE_CERT_START;
    cfg.credentials.authentication.key             = reinterpret_cast<const char*>(DEVICE_KEY_START);
    cfg.credentials.authentication.key_len         = DEVICE_KEY_END - DEVICE_KEY_START;
    cfg.credentials.client_id         = config::DEVICE_ID;
    // Reconnect with exponential backoff managed by the ESP-IDF MQTT client.
    // min_reconnect_backoff_ms defaults to 1 s, max to 60 s — acceptable for
    // Phase 3. No manual reconnect loop is needed.

    s_client = esp_mqtt_client_init(&cfg);
    if (!s_client) {
        ESP_LOGE(TAG, "Failed to initialise MQTT client — out of memory");
        return;
    }

    ESP_ERROR_CHECK(esp_mqtt_client_register_event(
        s_client, MQTT_EVENT_ANY, mqtt_event_handler, nullptr));

    ESP_ERROR_CHECK(esp_mqtt_client_start(s_client));
}

bool mqtt_publish_telemetry(const char* json, int len)
{
    if (!s_connected || !s_client) {
        ESP_LOGW(TAG, "MQTT not connected — telemetry sample dropped");
        return false;
    }

    // QoS 1: at-least-once delivery.
    // Duplicate messages are possible; the sequence number in the payload
    // allows downstream consumers to detect them when deduplication is
    // implemented in a later phase.
    int msg_id = esp_mqtt_client_publish(
        s_client, mqtt_config::TELEMETRY_TOPIC, json, len, /*qos=*/1, /*retain=*/0);

    if (msg_id < 0) {
        ESP_LOGW(TAG, "esp_mqtt_client_publish failed (msg_id=%d)", msg_id);
        return false;
    }

    ESP_LOGD(TAG, "Telemetry queued for publish (msg_id=%d)", msg_id);
    return true;
}

bool mqtt_is_connected()
{
    return s_connected;
}
